"""items

Revision ID: 36effc3090b2
Revises: 
Create Date: 2020-07-09 15:53:56.175689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36effc3090b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numb', sa.Integer(), nullable=True),
    sa.Column('typename', sa.String(), nullable=True),
    sa.Column('itemname', sa.String(), nullable=True),
    sa.Column('size_i', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
